name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL of the deployment to test against"
        required: true
        type: string
  repository_dispatch:
    types: [deno_deploy.build.routed]

permissions:
  contents: read

jobs:
  integration:
    name: Integration Tests
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.client_payload.revision.preview_url != null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: >-
            ${{ github.event_name == 'repository_dispatch'
                && github.event.client_payload.revision.branch
                || github.sha }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
          cache-dependency-path: deno.lock
      - run: deno task test:integration
        env:
          BASE_URL: >-
            ${{ github.event_name == 'workflow_dispatch'
                && inputs.base_url
                || github.event.client_payload.revision.preview_url }}
