name: Integration Tests

on:
  repository_dispatch:
    types: [deno_deploy.build.routed]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      PREVIEW_DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}
    steps:
      - name: Checkout dispatch branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.revision.branch }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            node_modules
          key: deno-${{ runner.os }}-${{ hashFiles('deno.lock') }}
          restore-keys: |
            deno-${{ runner.os }}-

      - name: Generate Prisma client
        run: deno task prisma:generate

      - name: Install dependencies
        run: deno install

      - name: Run migrations on preview database
        run: deno task prisma:migrate
        env:
          DATABASE_URL: ${{ env.PREVIEW_DATABASE_URL }}

      - name: Run integrations tests
        run: |
          echo "DEPLOY_URL: $BASE_URL"
          deno task test:integration
        env:
          BASE_URL: ${{ github.event.client_payload.revision.preview_url }}
          DATABASE_URL: ${{ env.PREVIEW_DATABASE_URL }}
